name: Fetch Notion

on:
  workflow_dispatch:
  schedule:
    - cron: "0 21 * * 0,3"

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-and-pr:
    name: Fetch and Create a Pull Request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - run: npm i -g pnpm @antfu/ni

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Install Dependencies
        run: nci

      - name: Fetch Associations
        env:
          NOTION_KEY: ${{ secrets.NOTION_KEY }}
          NOTION_ASSOCIATIONS_DATABASE_ID: ${{ secrets.NOTION_ASSOCIATIONS_DATABASE_ID }}
          NOTION_SCHOOLS_DATABASE_ID: ${{ secrets.NOTION_SCHOOLS_DATABASE_ID }}
          NOTION_CONTEST_PARTICIPATIONS_DATABASE_ID: ${{ secrets.NOTION_CONTEST_PARTICIPATIONS_DATABASE_ID }}
          NOTION_BATTLE_PARTICIPATIONS_DATABASE_ID: ${{ secrets.NOTION_BATTLE_PARTICIPATIONS_DATABASE_ID }}
          NOTION_CATEGORIES_DATABASE_ID: ${{ secrets.NOTION_CATEGORIES_DATABASE_ID }}

        run: nr fetch-notion

      - run: nr check-images

      - run: nr check-associations

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: feat-associations-automatic-update
          commit-message: "feat(associations): automatic update"
          title: "feat(content): automatic update"
          body: |
            Update `content` automatically using Notion data.

            Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          reviewers: Barbapapazes
